config/routes.rb
Rails.application.routes.draw do
  root 'attendances#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  patch 'attendances/finish' => 'attendances#finish', as: 'finish'
  
  resources :attendances do
    collection { post :import }
  end
  resources :users
  resources :holidays
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    validates :attendance_date, presence: true, uniqueness: { scope: :user_id }
    validate :valid_eligiblity_range?, on: :create
    validate :start_end_check, on: :update
    def start_time
        self.attendance_date #self.の後はsimple_calendarに表示させるためのカラムを指定
      end

    def valid_eligiblity_range?
        return unless leave_office_time? && attendance_time?
    
        if !leave_office_time.after?(attendance_time)
          errors.add(:leave_office_time, "の時間を正しく記入してください。")
        end
    end


    def start_end_check
        errors.add(:leave_office_time, "の時間は勤務開始より後の時刻でご登録ください。") unless
        self.attendance_time < self.leave_office_time
      end

    def self.import(file, current)
        CSV.foreach(file.path, headers: true) do |row|
            @attendance = find_or_initialize_by(attendance_date: row[1], user_id: current)
            if @attendance.new_record? 
              @attendance.save!(attendance_date: Date.today, user_id: current, validate: false)
            end
          
       if row[3] == '7001'
        @attendance.log_attendance_time = row[1]
      elsif row[3] == '7002'
        @attendance.log_leave_time = row[1]
       else
      
       end  
            @attendance.save!(validate: false)
        end
      
      
      end
     
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]
 
  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
    attendances = @attendances
    @attendances = current_user.attendances
    @user = current_user
    @attendance = Attendance.new
    
    
  end  

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  def import
    Attendance.import(params[:file], current_user.id)
    redirect_to root_path
  end


  

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)
    @attendance.user = current_user
   
    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendances_path(@attendance), notice: "今日も一日お疲れさまでした！" }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html {  
          redirect_to attendances_path(@attendance), notice: "登録したい勤怠日が重複しているか、出勤・退勤時刻の前後に間違いがある可能性があります。また打刻時間を変更したい場合は修正からお願いいたします。"
      }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendances_path(@attendance), notice: "勤怠の修正が完了いたしました。" }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "登録を削除いたしました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

   

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:attendance_time, :leave_office_time,:attendance_date )
    end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
       <%= form.label :勤務日　%>
       <%= form.date_select :attendance_date %>
     </div>

  <div class="field">
       <%= form.label :勤務開始 %>
       <%= form.time_select :attendance_time %>
     </div>
  
     <div class="field">
      <%= form.label :勤務終了 %>
      <%= form.time_select :leave_office_time %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  

<% end %>

app/views/attendances/_form2.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
    <% if attendance.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>
  
        <ul>
          <% attendance.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
     <div class="field">
       <%= form.label :勤務開始 %>
       <p>ログイン時刻:<%= @attendance&.log_attendance_time&.strftime("%-H時%-M分") %></p>
       <%= form.time_select :attendance_time %>
     </div>
  
     <div class="field">
      <%= form.label :勤務終了 %>
      <p>ログイン時刻:<%= @attendance&.log_leave_time&.strftime("%-H時%-M分") %></p>
      <%= form.time_select :leave_office_time %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
    
  
  <% end %>
  

app/views/attendances/edit.html.erb
<H4><%= @attendance.attendance_date.strftime("%Y年%-m月%-d日") %></H4>

<%= render 'form2', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<div class="container-fluid text-center">
<H4><%= Time.now.strftime("%Y年%-m月%-d日") %></H4>
<%= render 'form', attendance: @attendance %>

<H3><%= @user.name %>/スケジュール・実績一覧</H3>

<H5>ログアップロード</H5>
<%= form_tag import_attendances_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>


<div class="row">
<div class="col-2"></div>
<div class="col-8 d-flex justify-content-center">

<%= month_calendar(events: @attendances) do |date, attendances| %>
<%= date.day %>
  <% attendances.each do |attendance| %>
    
    <div>
     
     
        <td><%= attendance&.attendance_time&.strftime("%-H時%-M分") %></td>
        <td><%= attendance&.leave_office_time&.strftime("%-H時%-M分") %></td>
        <td><%= attendance&.log_attendance_time&.strftime("%-H時%-M分") %></td>
        <td><%= attendance&.log_leave_time&.strftime("%-H時%-M分") %></td>
        <td><%= link_to '修正', edit_attendance_path(attendance) %></td>
        <td><%= link_to '削除', attendance, method: :delete, data: { confirm: '本当によろしいですか?' } %></td>
      </div>
  <% end %>
<% end %>


</div>



<div class="col-2"></div>
</div>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p>
  <strong>Attendance time:</strong>
  <%= @attendance.attendance_time %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>