config/routes.rb
Rails.application.routes.draw do
  root 'attendances#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  patch 'attendances/finish' => 'attendances#finish', as: 'finish'
  
  resources :attendances do
    collection { post :import }
  end
  resources :users
  resources :holidays
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<p>© 2022 All Rights Reserved.</p>

</footer>

app/views/layouts/_header.html.erb
<header class="header">
 <div class="wrapper">
 <div class="logo">
  <%= image_tag 'torimono_logo.png', :size => '86x59'  %>
  </div>

  <div class="nav">
  <% if user_signed_in? %>
      <%= link_to "TOP", attendances_path, class: "btn" %>
      <%= link_to "申請・承認", holidays_path, class: "btn" %>
      <%= link_to "アカウント", user_path(current_user), class: "btn" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn" %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path, class: "btn" %>
      <%= link_to "ログイン", new_user_session_path, class: "btn" %>
    <% end %>
   </div>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Torimono</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render partial: "layouts/header" %>
<main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
</main>
<%= render partial: "layouts/footer" %>
  </body>
</html>